package com.cht.procurementManagement.enums;

public enum NotificationType {
    REQUEST_SUBMITTED,
    REQUEST_APPROVED_BY_ADMIN,
    REQUEST_REJECTED_BY_ADMIN,
    REQUEST_APPROVED_BY_SUPPLIES,
    REQUEST_REJECTED_BY_SUPPLIES,
    PROCUREMENT_CREATED,
    PROCUREMENT_STATUS_UPDATE
}
